import { StyleSheet } from 'react-native';
const styles = StyleSheet.create({
  gradientHeaderRefactored: {
    flexDirection: 'row',
    alignItems: 'center',
    borderBottomLeftRadius: 32,
    borderBottomRightRadius: 32,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 8,
    elevation: 4,
    zIndex: 1,
  },
  headerText: {
    color: '#fff',
    fontSize: 32,
    fontWeight: 'bold',
    lineHeight: 36,
  },
  avatar: {
    width: 64,
    height: 64,
    borderRadius: 32,
    marginLeft: 16,
    borderWidth: 2,
    borderColor: '#fff',
  },
  scamCardRefactored: {
    backgroundColor: '#fff',
    borderRadius: 20,
    padding: 18,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.07,
    shadowRadius: 8,
    elevation: 2,
  },
  inputWrapper: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#f5f5f5',
    borderRadius: 8,
    paddingHorizontal: 8,
    marginTop: 4,
  },
  alertRow: {
    flexDirection: 'row',
    gap: 12,
    marginBottom: 16,
  },
  alertCard: {
    flex: 2,
    backgroundColor: '#d6f0ff',
    borderRadius: 16,
    padding: 16,
    marginRight: 4,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.07,
    shadowRadius: 8,
    elevation: 2,
  },
  alertCardPlaceholder: {
    flex: 1,
    backgroundColor: '#e6f0fa',
    borderRadius: 16,
    alignItems: 'center',
    justifyContent: 'center',
    marginLeft: 4,
    minHeight: 120,
  },
  seeMoreBtn: {
    marginTop: 12,
    backgroundColor: '#FF7A2F',
    borderRadius: 8,
    alignSelf: 'flex-start',
    paddingHorizontal: 16,
    paddingVertical: 6,
  },
  seeMoreText: {
    color: '#fff',
    fontWeight: 'bold',
  },
  progressSection: {
    backgroundColor: '#fff',
    borderRadius: 16,
    padding: 16,
    flexDirection: 'column',
    gap: 12,
    marginBottom: 16,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.07,
    shadowRadius: 8,
    elevation: 2,
  },
  progressItemRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginBottom: 8,
  },
  progressItemLeft: {
    flexDirection: 'row',
    alignItems: 'center',
    flex: 1,
    gap: 8,
  },
  circleProgress: {
    width: 48,
    height: 48,
    borderRadius: 24,
    backgroundColor: '#f5f5f5',
    alignItems: 'center',
    justifyContent: 'center',
    marginRight: 8,
    position: 'relative',
  },
  circleFill: {
    position: 'absolute',
    top: 4,
    left: 4,
    backgroundColor: 'transparent',
    borderWidth: 4,
    borderColor: '#6A8DFF',
    borderRadius: 20,
  },
  progressLabel: {
    fontSize: 16,
    color: '#222',
    flex: 1,
  },
  progressValueRight: {
    fontWeight: 'bold',
    fontSize: 16,
    color: '#6A8DFF',
    minWidth: 48,
    textAlign: 'right',
  },
  shortcutsCard: {
    backgroundColor: '#ede3ff',
    borderRadius: 20,
    padding: 16,
    marginBottom: 24,
    marginTop: 8,
  },
  shortcutsRowAligned: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 0,
  },
  shortcutIconWrapAligned: {
    alignItems: 'center',
    flex: 1,
    justifyContent: 'center',
  },
  shortcutIconAligned: {
    width: 48,
    height: 48,
    marginBottom: 4,
    borderRadius: 12,
    backgroundColor: '#fff',
    alignItems: 'center',
    justifyContent: 'center',
    resizeMode: 'contain',
  },
  shortcutLabel: {
    fontSize: 13,
    color: '#222',
    marginTop: 2,
  },
  centered: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
  },
  uploadBox: {
    borderStyle: "dashed",
    borderWidth: 1.2,
    borderColor: "#ddd",
    borderRadius: 16,
    padding: 10,
    alignItems: "center",
    marginBottom: 10,
    backgroundColor: "#fafaff",
    marginTop: 2,
  },
  uploadText: {
    fontSize: 15,
    color: "#232042",
    marginBottom: 2,
    fontWeight: "500",
  },
  supportedFilesText: {
    fontSize: 12,
    color: "#aaa",
    marginBottom: 2,
  },
  selectedFileText: {
    fontSize: 13,
    color: "#6A8DFF",
    marginTop: 2,
  },
  container: {
    flex: 1,
    padding: 24,
    gap: 16,
    backgroundColor: '#fafbfc',
  },
  title: {
    fontSize: 28,
    fontWeight: "bold",
    color: "#232042",
    marginTop: 8,
    marginBottom: 12,
    letterSpacing: -0.5,
  },
  subtitle: {
    fontSize: 16,
    marginBottom: 12,
    color: "grey",
  },
  blackSubtitle: {
    fontSize: 16,
    marginBottom: 12,
  },
  link: {
    fontSize: 16,
    marginBottom: 8,
    fontWeight: "bold",
    textDecorationLine: "underline"
  },
  warning: {
    fontSize: 16,
    marginBottom: 8,
    color:"#a01919",
  },
  infoBox: {
    backgroundColor: "#E2F1FB",
    borderRadius: 10,
    padding: 15,
    marginTop: 15,
    marginBottom: 18,
  },
  // input: {
  //   borderWidth: 1,
  //   borderColor: '#bbb',
  //   borderRadius: 5,
  //   paddingHorizontal: 12,
  //   backgroundColor: 'transparent',
  //   textAlignVertical: 'top',
  //   height: 300,
  //   fontSize: 16,
  //   marginBottom: 18
  // },
  input: {
  borderWidth: 1.5,
  borderColor: "#eee",
  borderRadius: 16,            
  paddingHorizontal: 18,
  paddingTop: 22,
  paddingBottom: 18,
  backgroundColor: "#F7F8FA", 
  textAlignVertical: "top",
  minHeight: 100,
  maxHeight: 220,
  fontSize: 16,
  color: "#232042",
  marginBottom: 18,
  elevation: 4,                  // for Android shadow
  // Optional: Add a border glow on focus if using a custom wrapper
  // borderColor: isFocused ? "#745ff2" : "#dad7f5",
},
  smallInput: {
      height: 44,
      borderRadius: 12,
      borderWidth: 1.2,
      borderColor: "#eee",
      backgroundColor: "#F7F8FA",
      paddingHorizontal: 16,
      fontSize: 16,
      marginBottom: 12,
    },

  inputTransparent: {
    flex: 1,
    height: 40,
    fontSize: 16,
    backgroundColor: 'transparent',
    borderWidth: 0,
    marginLeft: 8,
    color: '#222',
  },
  attachButton: {
    paddingVertical: 8,
    alignItems: 'center',
  },
  attachmentBox: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
    backgroundColor: '#f0f2f5',
    borderRadius: 8,
    padding: 10,
  },
  attachmentName: {
    flex: 1,
    color: '#555',
    fontSize: 15,
  },
  removeAttachment: {
    color: '#d00',
    fontWeight: '600',
    marginLeft: 10,
  },
  attachmentImage: {
    width: 40,
    height: 40,
    borderRadius: 6,
    marginRight: 10,
  },
  attachmentIcon: {
    fontSize: 28,
    marginRight: 10,
  },
  submitBtn: {
    backgroundColor: "#3D5CFF",
    borderRadius: 12,
    paddingVertical: 12,
    alignItems: "center",
    marginTop: 5,
    marginBottom: 18,
    shadowColor: "#3D5CFF",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.14,
    shadowRadius: 3,
    elevation: 2,
    flexDirection: "row",
    justifyContent: "center",
  },
  submitBtnText: {
    color: "#fff",
    fontSize: 17,
    fontWeight: "700",
  },
  
  altText: {
    alignSelf: "center",
    color: "#888",
    fontSize: 15,
    marginBottom: 8,
  },
  modalContainer: {
    flex: 1,
    backgroundColor: "rgba(30,30,30,0.85)",
    justifyContent: "center",
    alignItems: "center",
  },
  camera: {
    width: 320,
    height: 400,
    borderRadius: 20,
    overflow: "hidden",
    marginBottom: 30,
  },
  modalActions: {
    position: "absolute",
    bottom: 60,
    left: 0,
    right: 0,
    alignItems: "center",
  },
  modalOverlay: {
    flex: 1,
    backgroundColor: "rgba(0,0,0,0.5)",
    justifyContent: "center",
    alignItems: "center",
  },
  modalContent: {
    width: "85%",
    backgroundColor: "#fff",
    padding: 20,
    elevation: 5,
  },
  singleModalContent: {
    width: "85%",
    backgroundColor: "#fff",
    borderRadius: 15,
    padding: 20,
    elevation: 5,
  },
  rowCenter: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    marginBottom: 15,
  },
  warningText: {
    color: "#F36C5E",
    fontSize: 18,
    fontWeight: "bold",
    textAlign: "center",
  },
  safeText: {
    color: "#4FE87C",
    fontSize: 18,
    fontWeight: "bold",
    textAlign: "center",
  },
  stepsText: {
    color: "#000",
    fontSize: 16,
    fontWeight: "bold",
    lineHeight: 25,
    marginTop: 8,
  },
  closeButton: {
    marginTop: 20,
    backgroundColor: "#3D5CFF",
    paddingVertical: 10,
    borderRadius: 6,
    alignItems: "center",
  },
  messageModal: {
    alignItems: "center", 
    justifyContent: "center", 
    marginVertical: 10, 
    marginHorizontal: 10, 
    gap: 8 
  }
}); 

export default styles;
