import { StyleSheet } from 'react-native';

const styles = StyleSheet.create({
  gradientHeaderRefactored: {
    flexDirection: 'row',
    alignItems: 'center',
    borderBottomLeftRadius: 32,
    borderBottomRightRadius: 32,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 8,
    elevation: 4,
    zIndex: 1,
  },
  headerText: {
    color: '#fff',
    fontSize: 32,
    fontWeight: 'bold',
    lineHeight: 36,
  },
  avatar: {
    width: 64,
    height: 64,
    borderRadius: 32,
    marginLeft: 16,
    borderWidth: 2,
    borderColor: '#fff',
  },
  scamCardRefactored: {
    backgroundColor: '#fff',
    borderRadius: 20,
    padding: 18,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.07,
    shadowRadius: 8,
    elevation: 2,
  },
  inputWrapper: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#f5f5f5',
    borderRadius: 8,
    paddingHorizontal: 8,
    marginTop: 4,
  },
  input: {
    flex: 1,
    height: 40,
    fontSize: 16,
    backgroundColor: 'transparent',
    borderWidth: 0,
    marginLeft: 8,
    color: '#222',
  },
  alertRow: {
    flexDirection: 'row',
    gap: 12,
    marginBottom: 16,
  },
  alertCard: {
    flex: 2,
    backgroundColor: '#d6f0ff',
    borderRadius: 16,
    padding: 16,
    marginRight: 4,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.07,
    shadowRadius: 8,
    elevation: 2,
  },
  alertCardPlaceholder: {
    flex: 1,
    backgroundColor: '#e6f0fa',
    borderRadius: 16,
    alignItems: 'center',
    justifyContent: 'center',
    marginLeft: 4,
    minHeight: 120,
  },
  seeMoreBtn: {
    marginTop: 12,
    backgroundColor: '#FF7A2F',
    borderRadius: 8,
    alignSelf: 'flex-start',
    paddingHorizontal: 16,
    paddingVertical: 6,
  },
  seeMoreText: {
    color: '#fff',
    fontWeight: 'bold',
  },
  progressSection: {
    backgroundColor: '#fff',
    borderRadius: 16,
    padding: 16,
    flexDirection: 'column',
    gap: 12,
    marginBottom: 16,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.07,
    shadowRadius: 8,
    elevation: 2,
  },
  progressItemRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginBottom: 8,
  },
  progressItemLeft: {
    flexDirection: 'row',
    alignItems: 'center',
    flex: 1,
    gap: 8,
  },
  circleProgress: {
    width: 48,
    height: 48,
    borderRadius: 24,
    backgroundColor: '#f5f5f5',
    alignItems: 'center',
    justifyContent: 'center',
    marginRight: 8,
    position: 'relative',
  },
  circleFill: {
    position: 'absolute',
    top: 4,
    left: 4,
    backgroundColor: 'transparent',
    borderWidth: 4,
    borderColor: '#6A8DFF',
    borderRadius: 20,
  },
  progressLabel: {
    fontSize: 16,
    color: '#222',
    flex: 1,
  },
  progressValueRight: {
    fontWeight: 'bold',
    fontSize: 16,
    color: '#6A8DFF',
    minWidth: 48,
    textAlign: 'right',
  },
  shortcutsCard: {
    backgroundColor: '#ede3ff',
    borderRadius: 20,
    padding: 16,
    marginBottom: 24,
    marginTop: 8,
  },
  shortcutsRowAligned: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 0,
  },
  shortcutIconWrapAligned: {
    alignItems: 'center',
    flex: 1,
    justifyContent: 'center',
  },
  shortcutIconAligned: {
    width: 48,
    height: 48,
    marginBottom: 4,
    borderRadius: 12,
    backgroundColor: '#fff',
    alignItems: 'center',
    justifyContent: 'center',
    resizeMode: 'contain',
  },
  shortcutLabel: {
    fontSize: 13,
    color: '#222',
    marginTop: 2,
  },
  centered: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
  },
}); 

export default styles;
